apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
  containers:
  - name: hellopod
    image: ghcr.io/sdsu-research-ci/hello-sdsu:main
    resources:
      limits:
        memory: 100Mi
        cpu: 100m
      requests:
        memory: 100Mi
        cpu: 100m
    command: ["sh", "-c", "sleep infinity"]
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - 'key': 'nautilus.io/sdsuinstruction'
            'operator': 'In'
            'values': ["true"]
  tolerations:
    - effect: NoSchedule
      key: nautilus.io/sdsu-fix
      operator: Exists
